/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Audio: typeof import('./src/components/preview/components/Audio.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    Code: typeof import('./src/components/preview/components/Code.vue')['default']
    DeleteFile: typeof import('./src/components/FileAction/components/DeleteFile.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Doc: typeof import('./src/components/preview/components/Doc.vue')['default']
    EditableCell: typeof import('./src/components/Table/src/components/editable/EditableCell.vue')['default']
    FileAction: typeof import('./src/components/FileAction/FileAction.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    FolderSelect: typeof import('./src/components/FileAction/components/FolderSelect.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Image: typeof import('./src/components/preview/components/Image.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Other: typeof import('./src/components/preview/components/Other.vue')['default']
    Popover: typeof import('./src/components/preview/components/Popover.vue')['default']
    Preview: typeof import('./src/components/preview/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareFile: typeof import('./src/components/FileAction/components/ShareFile.vue')['default']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar.vue')['default']
    UploadPassword: typeof import('./src/components/UploadPassword.vue')['default']
    Video: typeof import('./src/components/preview/components/Video.vue')['default']
    Window: typeof import('./src/components/Window.vue')['default']
    Window2: typeof import('./src/components/Window2.vue')['default']
  }
}
